language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t andre1050/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true andre1050/docker-react npm run test -- --coverage
